from tkinter import *
from tkinter import ttk
from tkinter import messagebox

root = Tk()  # main container...
root.title("Login Page")  # title of the main container...
root.geometry('400x100')  # width = 400 , height = 100
root.resizable(False, False)  # resizable property is disabled...
frame = ttk.Frame(root)  # main frame to contain all elements...
frame.pack()  # placing the frame into the container...
l1 = ttk.Label(frame, text="User name:")  # user name label...
l1.grid(row=0, column=0)
etUserName = ttk.Entry(frame, width=20)  # input field for user name...
etUserName.grid(row=0, column=1)
l2 = ttk.Label(frame, text="Password:")  # password label...
l2.grid(row=1, column=0)
etPassword = ttk.Entry(frame, width=20)  # input field for password...
etPassword.grid(row=1, column=1)
etPassword.config(show="*")  # encrypting the password with *...
Bulogin = ttk.Button(frame, text="Login")  # login button
Bulogin.grid(row=2, column=1)


def BuClick():
    print("User name:{}, Password: {}".format(etUserName.get(), etPassword.get()))
    if (etUserName.get() == "admin" and etPassword.get() == "1234"):
        messagebox.showinfo(title="Login info", message="Welcome into python App")
    else:
        messagebox.showinfo(title="Login info", message="User name or password is incorrect")


Bulogin.config(command=BuClick)  # if the login button clicked execute BuClick method...

root.mainloop()  # show the container...
